// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWon5ngyZuuxG-bUILH_MUsEpCd4vhE-U',
    appId: '1:451873266:web:295fc296b0c0f812ce436b',
    messagingSenderId: '451873266',
    projectId: 'taxi-app-297ec',
    authDomain: 'taxi-app-297ec.firebaseapp.com',
    storageBucket: 'taxi-app-297ec.appspot.com',
    measurementId: 'G-6FMYNCHW66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGnv-3nfYvmlGn43lRflEJX3DZjgJn-p0',
    appId: '1:451873266:android:8d6718ce0cde0b8bce436b',
    messagingSenderId: '451873266',
    projectId: 'taxi-app-297ec',
    storageBucket: 'taxi-app-297ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcK1HR1wdpj6d_OCQN1sKwXzcrUF7Ly24',
    appId: '1:451873266:ios:2a6df5ff319fd52ece436b',
    messagingSenderId: '451873266',
    projectId: 'taxi-app-297ec',
    storageBucket: 'taxi-app-297ec.appspot.com',
    iosBundleId: 'com.taxi.customer.taxiCustomerDemo1',
  );
}
